### ISSUE TITLE
Addition/Removal of Orders

### ISSUE THREAD

**Issue by rrtheonlyone** [CS2103-AY1819S1-T16-3/main#10]
In order to morph AB4 to FoodZoom, we need to allow for the addition and removal of orders.

This is a change which requires:
- [x] Change in Storage Structure (xml files to store order information)
- [x] Change in Modal 
- [x] Change in Logic (add new commands + parsing for those commands)
- [x] Simple Change in UI handles

**Comment by juxd** [comment]
We'll need to have a discussion on how our storage structure should look.
