### ISSUE TITLE
Adding Route

### ISSUE THREAD

**Issue by monmanuela** [CS2103-AY1819S1-T16-3/main#14]
FoodZoom needs to support the assigning a route to deliveryman. In V1.1, we only consider single order routes (1 route only has 1 order).

This requires:

- [x] Designing a Route class
- [x] Change in Storage Structure (xml file to store route information)
- [ ] Change in Logic (add commands relevant to /route and /assign, and parse)
- [ ] Assign the route to a deliveryman (implementation tbc)

**Comment by juxd** [comment]
we can move this to 1.2? or have you worked on it already

**Comment by monmanuela** [comment]
Moving to v1.2:
- Adding Order to Route
