### ISSUE TITLE
Signup allows 2 users with different name but same username and password

### ISSUE THREAD

**Issue by monmanuela** [CS2103-AY1819S1-T16-3/main#156]
`/signup n/Monikaz u/mon pw/monika`
`/signup n/Monikax u/mon pw/monika`
consecutively are allowed, which makes `/login u/mon pw/monika` confusing as it isn't clear if this is for user "Monikaz" or "Monikax". Maybe can consider forcing unique username.

**Comment by kohchihao** [comment]
Or I remove `name` completely?

**Comment by monmanuela** [comment]
Can also, so the user's unique identifier is the username?
