### ISSUE TITLE
Add resources to Deliveryman model

### ISSUE THREAD

**Issue by juxd** [CS2103-AY1819S1-T16-3/main#28]
For V1.2

This includes: 
- [ ] Adding `Route`s to `Deliveryman`
- [ ] Modifying XML storage classes to accommodate `XmlIdRef`
- [ ] Modifying `Storage`/`Model` managers to read & write across XML files
- [ ] Timer for routes

**Comment by kohchihao** [comment]
#57

**Comment by juxd** [comment]
This feature was migrated to 1.3 because in v1.2 a necessary feature (#59) was implemented to allow this.
